server:
  port: 8762
spring:
  application:
    name: ZULL SERVER
zuul:
  ignoredServices: '*'
  routes:
    userapi:
      path: /userapi/**
      service-id: USER-SERVICE
      strip-prefix: true
    storyapi:
      path: /storyapi/**
      service-id: STORY-SERVICE
      strip-prefix: true
    commentapi:
      path: /commentapi/**
      service-id: COMMENT-SERVICE
      strip-prefix: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka